trigger:
- 'develop'

jobs:
- job: build_linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - checkout: self
    submodules: true
  - bash: 'sudo apt install -y libev-dev libcunit1-dev'
  - bash: 'autoreconf --install'
  - bash: './configure CPPFLAGS=-DNDEBUG'
  - bash: 'make'
- job: build_windows_x86
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: self
    submodules: true
  - task: MSBuild@1
    inputs:
      solution: 'msvc/trudp.sln' 
      platform: x86
      configuration: Release
      msbuildArguments: -target:trudp-static
- job: build_windows_x86_64
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: self
    submodules: true
  - task: MSBuild@1
    inputs:
      solution: 'msvc/trudp.sln' 
      platform: x64
      configuration: Release
      msbuildArguments: -target:trudp-static
